### ISSUE TITLE
API bevezetése

### ISSUE THREAD

**Issue by foxi69** [cu2/KT#59]
publikus webapi készítésén gondolkoztatok?

**Comment by pvj** [comment]
Lehet akkor mindossze a masodik, harmadik ember vagyok de en miota megismertem a Kt-t ugyanezen gondolkodok. Mindenfele nyomas nelkul, csak gondoltam jelzem itt egy piciny szereny kommentben 

A publik API amugy azt hiszem mindig egy klasszikus tyuk-tojas, ki tudja, nem-e akkor none meg az igeny, ha mar elerhetove valna es par mekkajaro elkezdene mobil-verziokat, import/exportalokat stb. fejleszteni. 

(Mivel eloszor kommentalok ezen a repon szeretnem megkoszonni es kalapom emelni a nagyszeru szolgaltatasert amit magyaroknak, magyar kulturanak nyujtasz immar ilyen tavlatokban merheto ideje, hogy evtizedes! Mega grat!!!)
